<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="ICIX Test For sdd"
           tests="1"
           failures="1"
           errors="0"
           skipped="0"
           time="262.162">
  <properties />
            <testcase name="testSearchByIcixId" time="262.162" classname="icix.Tests.TC9649_Test">
                <failure type="java.lang.AssertionError"
                  message="expected [We found 1 match in the ICIX Network.] but found [We found No matches in the ICIX Network.]"
              >
<![CDATA[java.lang.AssertionError: expected [We found 1 match in the ICIX Network.] but found [We found No matches in the ICIX Network.]
  org.testng.Assert.fail(Assert.java:94)
  org.testng.Assert.failNotEquals(Assert.java:513)
  org.testng.Assert.assertEqualsImpl(Assert.java:135)
  org.testng.Assert.assertEquals(Assert.java:116)
  org.testng.Assert.assertEquals(Assert.java:190)
  org.testng.Assert.assertEquals(Assert.java:200)
  icix.Utils.Common.assertText(Common.java:548)
  icix.Modules.Account.searchTPBy(Account.java:50)
  icix.Tests.TC9649_Test.testSearchByIcixId(TC9649_Test.java:31)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
  org.testng.TestRunner.privateRun(TestRunner.java:782)
  org.testng.TestRunner.run(TestRunner.java:632)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
  org.testng.SuiteRunner.run(SuiteRunner.java:268)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
  org.testng.TestNG.run(TestNG.java:1064)
  org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
      </failure>

          </testcase>
  
  
  
</testsuite>
