<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="1406498" started-at="2016-11-23T07:55:56Z" finished-at="2016-11-23T08:19:22Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="1406498" started-at="2016-11-23T07:55:56Z" finished-at="2016-11-23T08:19:22Z">
      <class name="com.org.Example.myproject.TC9733_Test">
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:com.org.Example.myproject.TC9733_Test@1ffadfdf]" name="beforeClass" is-config="true" duration-ms="26146" started-at="2016-11-23T13:25:56Z" finished-at="2016-11-23T13:26:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="FAIL" signature="Approve_Request()[pri:0, instance:com.org.Example.myproject.TC9733_Test@1ffadfdf]" name="Approve_Request" duration-ms="1380331" started-at="2016-11-23T13:26:22Z" finished-at="2016-11-23T13:49:22Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Workflow status is not closed expected [Closed] but found [Open]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Workflow status is not closed expected [Closed] but found [Open]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at com.org.Example.myproject.TC9733_Test.Approve_Request(TC9733_Test.java:110)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Approve_Request -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:com.org.Example.myproject.TC9733_Test@1ffadfdf]" name="afterClass" is-config="true" duration-ms="0" started-at="2016-11-23T13:49:22Z" finished-at="2016-11-23T13:49:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- com.org.Example.myproject.TC9733_Test -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
